import type { Metadata } from "next";
import "./css/style.css";
import "./css/font-icons.css";
import "./css/custom.css";
import Header from "./components/Header";
import CanvasScripts from "./components/CanvasScripts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="stretched">
        <div id="wrapper">
          <Header />
          {children}
        </div>

        <CanvasScripts />
      </body>
    </html>
  );
}
